// <auto-generated />
using System;
using Api.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<bool>("HandleAllDivision")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NIP")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("SendEmailNotification")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8884ac-e5ff-4ab2-92f6-5c328d2f6e97"),
                            Created = new DateTime(2024, 8, 21, 10, 12, 34, 0, DateTimeKind.Unspecified),
                            Email = "superadmin@admin.com",
                            FullName = "Super Admin",
                            HandleAllDivision = false,
                            PasswordHash = "$2a$11$f5E2RfGFfjSUi8IaMZcQzOEtsNYBDl2077tPMztZU.j0eeiRJDoQO",
                            RoleId = new Guid("9648fc11-a4bf-40bb-84a2-2925ebaa630d"),
                            SendEmailNotification = false,
                            Status = 0,
                            Username = "superadmin",
                            Verified = new DateTime(2024, 8, 21, 10, 12, 34, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dc323466-0729-4f4c-82c4-43560ae1113c"),
                            Created = new DateTime(2024, 8, 21, 10, 12, 34, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com",
                            FullName = "Admin",
                            HandleAllDivision = false,
                            PasswordHash = "$2a$11$g0hpbIHewxnYhIz85wSV9.lg1mUOOJlclLEs5ixBIeAk6ZZEinrjy",
                            RoleId = new Guid("0c4db327-d216-43ab-b7de-3898e8f72add"),
                            SendEmailNotification = false,
                            Status = 0,
                            Username = "admin",
                            Verified = new DateTime(2024, 8, 21, 10, 12, 34, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entity")
                        .HasColumnType("longtext");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("From")
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .HasColumnType("longtext");

                    b.Property<string>("Service")
                        .HasColumnType("longtext");

                    b.Property<string>("To")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Api.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageBig")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageDefault")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageSmall")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageType")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Api.Entities.NavigationMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PermissionMethod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("NavigationMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5c9220d-8997-4607-b34b-7c5a63c97b84"),
                            ControllerName = "dashboard-user",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = new Guid("4adece20-8676-4937-8479-2c6ca6c9ec7a"),
                            Name = "Management User",
                            Order = 1,
                            PermissionMethod = 15
                        },
                        new
                        {
                            Id = new Guid("cdf366d8-2936-45a3-b740-7441815161be"),
                            ControllerName = "dashboard-role",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = new Guid("4adece20-8676-4937-8479-2c6ca6c9ec7a"),
                            Name = "Management Role",
                            Order = 2,
                            PermissionMethod = 15
                        },
                        new
                        {
                            Id = new Guid("bc4f03bb-7bf2-492d-b0d8-2d688f2617c7"),
                            ControllerName = "audit-log",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Audit Log",
                            Order = 3,
                            PermissionMethod = 15
                        },
                        new
                        {
                            Id = new Guid("cb9a248e-585b-4055-bd25-67e5fe49bfcf"),
                            ControllerName = "site-config",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = new Guid("ef93b0ac-aea0-4080-bd4e-89e4052fea12"),
                            Name = "Site Config",
                            Order = 4,
                            PermissionMethod = 15
                        });
                });

            modelBuilder.Entity("Api.Entities.NavigationMenuGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NavigationMenuGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4adece20-8676-4937-8479-2c6ca6c9ec7a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Account"
                        },
                        new
                        {
                            Id = new Guid("ef93b0ac-aea0-4080-bd4e-89e4052fea12"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Setting"
                        });
                });

            modelBuilder.Entity("Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("NeedApproval")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OnlyShowDivisionConsultation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OnlyShowOwnConsultation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OnlyShowPerangkatDaerahConsultation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9648fc11-a4bf-40bb-84a2-2925ebaa630d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedApproval = false,
                            OnlyShowDivisionConsultation = false,
                            OnlyShowOwnConsultation = false,
                            OnlyShowPerangkatDaerahConsultation = false,
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            Id = new Guid("0c4db327-d216-43ab-b7de-3898e8f72add"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedApproval = false,
                            OnlyShowDivisionConsultation = false,
                            OnlyShowOwnConsultation = false,
                            OnlyShowPerangkatDaerahConsultation = false,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("Api.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NavigationMenuId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PermissionMethod")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NavigationMenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8fd6452-6930-41d0-a13e-e1fd09914261"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavigationMenuId = new Guid("f5c9220d-8997-4607-b34b-7c5a63c97b84"),
                            PermissionMethod = 15,
                            RoleId = new Guid("0c4db327-d216-43ab-b7de-3898e8f72add")
                        },
                        new
                        {
                            Id = new Guid("dec0458d-8964-4bc1-87da-7b8e5b4c58ba"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavigationMenuId = new Guid("cdf366d8-2936-45a3-b740-7441815161be"),
                            PermissionMethod = 15,
                            RoleId = new Guid("0c4db327-d216-43ab-b7de-3898e8f72add")
                        },
                        new
                        {
                            Id = new Guid("81a067f3-4e2f-42b0-b5eb-79e79f0f6a7a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavigationMenuId = new Guid("bc4f03bb-7bf2-492d-b0d8-2d688f2617c7"),
                            PermissionMethod = 15,
                            RoleId = new Guid("0c4db327-d216-43ab-b7de-3898e8f72add")
                        },
                        new
                        {
                            Id = new Guid("a0e0490b-3523-4b07-9bb9-3ca7276d9378"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavigationMenuId = new Guid("cb9a248e-585b-4055-bd25-67e5fe49bfcf"),
                            PermissionMethod = 15,
                            RoleId = new Guid("0c4db327-d216-43ab-b7de-3898e8f72add")
                        });
                });

            modelBuilder.Entity("Api.Entities.SiteConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SiteConfigs");
                });

            modelBuilder.Entity("Api.Entities.Account", b =>
                {
                    b.HasOne("Api.Entities.Media", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("Api.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Api.Entities.AuditLog", b =>
                {
                    b.HasOne("Api.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Api.Entities.Media", b =>
                {
                    b.HasOne("Api.Entities.Account", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Api.Entities.NavigationMenu", b =>
                {
                    b.HasOne("Api.Entities.NavigationMenuGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("Api.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Api.Entities.RolePermission", b =>
                {
                    b.HasOne("Api.Entities.NavigationMenu", "NavigationMenu")
                        .WithMany()
                        .HasForeignKey("NavigationMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Role", "Role")
                        .WithMany("RolePermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavigationMenu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Api.Entities.Account", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Api.Entities.Role", b =>
                {
                    b.Navigation("RolePermission");
                });
#pragma warning restore 612, 618
        }
    }
}
